[phases.setup]
nixPkgs = ['php82', 'php82Extensions.curl', 'php82Extensions.mbstring', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.tokenizer', 'php82Extensions.xml', 'nodejs_20', 'npm']

[phases.install]
cmds = [
  "composer config --no-plugins allow-plugins.pestphp/pest-plugin true",
  "composer install --no-dev --optimize-autoloader --no-interaction --no-progress",
]

[phases.build]
cmds = [
  "php artisan config:clear",
  "php artisan route:clear",
  "php artisan view:clear",
  "php artisan cache:clear"
]

[start]
cmd = "php artisan serve --host 0.0.0.0 --port ${PORT:-8000}"
