[build]
builder = "nixpacks"
buildCommand = "composer update --no-dev --ignore-platform-reqs && php artisan key:generate"

[deploy]
startCommand = "php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[phases.setup]
aptPkgs = ["php8.2", "php8.2-xml", "php8.2-curl", "php8.2-mbstring", "php8.2-mysql", "php8.2-gd", "php8.2-zip", "php8.2-bcmath", "php8.2-intl", "php8.2-sqlite3", "php8.2-pdo-sqlite", "php8.2-pdo-mysql"]

[variables]
PHP_ENABLE_INTL = "true"
